#summary Overview of how to work with get-flash-videos
#labels Featured,Phase-Implementation

First it's important to understand that the distributed `get_flash_videos`
differs from the version you'll find in the repository. This is to make
distribution easy (just one file for people to install, the update mechanism
can only update the one file, etc).

However it's obviously easier to develop on if the code is modular. This means
adding a site (see AddingSite) is just a matter of adding a site specific
module.  The code can also be run in either form, so that there is no need to
generate a combined version while developing.

These combined versions are generated by a Makefile and the script
`combine-perl.pl`, generating them is just a matter of typing `make`.

When you're working on `get_flash_videos`, please try to keep the "just works"
nature of the script. We mostly just want the script to be given a URL as a
parameter, and then "just work" - options shouldn't be necessary for normal
usage.

You can get the source from github. If you'd like to fix any of the open issues, add support for another site or add new features, please fork the project on github and send us a pull request.